substitutions:
  _LATEST_TAG: ${_IMAGE}:latest
  _COMMIT_TAG: ${_IMAGE}:${COMMIT_SHA}
  _CD_TRIGGER_NAME: ${_TRIGGER_NAME}
  _CD_TRIGGER_REGION: ${_TRIGGER_REGION}

steps:
  - name: 'alpine'
    id: 'print tags'
    entrypoint: 'sh'  
    args: 
    - '-c'
    - | 
        echo "***********************"
        echo "$_LATEST_TAG"
        echo "$_COMMIT_TAG
        echo "***********************"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args: ['build', '-t', '${_LATEST_TAG}', '-t', '${_COMMIT_TAG}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image to Artifact Registry'
    args: ['push', '${_IMAGE}']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Trigger CD pipeline'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        if [[ "$BRANCH_NAME" == "prod" || "$BRANCH_NAME" == "dev" ]]; then
          gcloud builds triggers run ${_TRIGGER_NAME} \
            --branch=${BRANCH_NAME} \
            --region=${_TRIGGER_REGION} \
            --substitutions=_IMAGE=${_LATEST_TAG},_COMMIT_SHA=${COMMIT_SHA} \
            --project=${PROJECT_ID}
        else
          echo "Skipping trigger for branch: $BRANCH_NAME"
        fi
    # args: [
    #   'builds',
    #   'triggers',
    #   'run',
    #   'dbt-cd-trigger-test',
    #   '--branch', 'feature/terraform-module',
    #   '--region', 'europe-west2' ]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s